CREATE TABLE JOB (
    JOB_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    START_TIME DATETIME NOT NULL,
    STATUS ENUM('FAILED_CRAWLER', 'FINISHED', 'STARTED', 'DB_ERRORS_MUCH') NOT NULL DEFAULT 'STARTED',
    END_TIME DATETIME  NOT NULL) ENGINE=INNODB DEFAULT CHARACTER SET utf8 ;
