CREATE TABLE SITE (
    SITE_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    URL VARCHAR(128) NOT NULL UNIQUE,
    RESOURCE_URL VARCHAR(128) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(128) NOT NULL,
    CONSTRAINT UX_SITE_URL UNIQUE INDEX (URL)) ENGINE=INNODB DEFAULT CHARACTER SET utf8 ;

CREATE TABLE ARTICLE (
    ARTICLE_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CONTENT MEDIUMTEXT CHARACTER SET utf8 NOT NULL,
    ORIGINAL_ARTICLE_URL VARCHAR(512) NOT NULL,
    TITLE VARCHAR(512) CHARACTER SET utf8 NOT NULL
--    ,
--    FK_SITE_ID INTEGER NOT NULL,
--    FOREIGN KEY (FK_SITE_ID) REFERENCES SITE(SITE_ID)
    ) ENGINE=INNODB DEFAULT CHARACTER SET utf8;