CREATE TABLE CREDENTIAL (
    CREDENTIAL_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(32) CHARACTER SET utf8 NOT NULL,
    PASSWORD VARCHAR(32) CHARACTER SET utf8 NOT NULL,
    FK_SITE_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_SITE_ID) REFERENCES SITE(SITE_ID)) ENGINE=INNODB DEFAULT CHARACTER SET utf8 ;
