ALTER TABLE JOB ADD COLUMN STATUS VARCHAR(16) NOT NULL;
ALTER TABLE JOB ADD COLUMN CRAWLER_ERRORS_COUNT INTEGER NOT NULL DEFAULT 0;
ALTER TABLE JOB ADD COLUMN DATABASE_ERRORS_COUNT INTEGER NOT NULL DEFAULT 0;