CREATE TABLE RECOMMENDATION (
    RECOMMENDATION_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    VOTE BOOLEAN NOT NULL,
    FK_ARTICLE_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_ARTICLE_ID) REFERENCES ARTICLE(ARTICLE_ID)) ENGINE=INNODB DEFAULT CHARACTER SET utf8;
